name: Trigger auto deployment for demo-vadder

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-vadder-AutoDeployTrigger-1047f878-acd7-4136-a9b3-73f3afc586ea.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEMOVADDER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMOVADDER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMOVADDER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: demovadda.azurecr.io
          registryUsername: ${{ secrets.DEMOVADDER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOVADDER_REGISTRY_PASSWORD }}
          containerAppName: demo-vadder
          resourceGroup: Vadda-ML
          imageToBuild: demovadda.azurecr.io/demo-vadder:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


